# Основные настройки
main_settings:
  # Команда рандомной телепортации (указывается без /)
  rtp_command: 'rtp'
  # Название дефолтного канала.
  # Указанный канал будет использован в качестве основного при вводе команды /rtp
  default_channel: 'default'
  # Отправлять ли анонимную статистику (советую не отключать)
  enable_metrics: true
  # Проверять ли на наличие обновлений (советую не отключать)
  update-checker: true

# Каналы рандомной телепортации
channels:
  # Базовый канал (право на использование - rtp.channel.имя_канала т.е. в данном случае rtp.channel.default)
  default:
    # Название канала (используется в плейсхолдерах)
    name: 'Стандартный'
    # Режим работы канала
    # DEFAULT - стандартный режим работы (просто телепортирует на рандомные координаты)
    # NEAR_PLAYER - телепортирует игрока рядом с другими игроками (/rtp player проще говоря)
    # NEAR_REGION - телепортирует игрока рядом с регионом worldguard (/rtp base проще говоря)
    type: DEFAULT
    # Миры в которых действует канал
    # Если игрок телепортируется по данному каналу в одном из этих миров - телепорт будет именно в этом мире
    active_worlds:
      - 'world'
      - 'world_nether'
      - 'world_the_end'
    # Должен ли канал телепортировать игрока в тот мир, который будет первым в списке active_worlds 
    # в случае если игрок пытается телепортироваться через него из другого мира? (полезно в случае, если канал должен вызываться из мира спавна например)
    teleport_to_first_world: true
    # Телепортировать ли игрока если тот упал ниже 0 координаты?
    # Полезно использовать если нужен телепорт после падения в яму
    teleport_on_void: false
    # Цена телепортации по данному каналу (используется vault api, -1 чтобы отключить)
    teleport_cost: -1
    # Принцип выбора локации
    location_generation_options:
      # Форма заготовки для поиска локации.
      # SQUARE - прямоугольник. При нем min_x/z и max_x/z являются 2мя противоположными сторонами прямоугольника.
      # ROUND - круг. При нем min_x/z и max_x/z являются 2мя противоположными сторонами прямоугольника, через который будет построен круг (или овал), вписывающийся в данный прямоугольник
      shape: SQUARE
      # Координаты
      min_x: -1000
      max_x: 1000
      min_z: -1000
      max_z: 1000
    # Максимальное кол-во попыток найти локацию для телепорта (нужно, чтобы не застрять в бесконечном цикле поиска локации)
    max_location_attemps: 50
    # Сколько тиков игрок должен быть неуязвим после телепортации через канал RTP (-1 чтобы отключить)
    invulnerable_after_teleport: 3
    # Кулдаун на телепортации в секундах (-1 чтобы отключить)
    cooldown: 60
    # Кулдаун до телепортации в секундах (-1 чтобы отключить)
    teleport_cooldown: 5
    # Настройка боссбара обратного отсчета
    # Не активен, если кулдаун до телепортации < 0
    bossbar:
      # Включить ли босс-бар
      enabled: true 
      # Настройки боссбара
      title: '&fТелепортация через: &5%time%'
      color: WHITE
      style: SEGMENTED_12
    # Запреты, которые накладываются на игрока перед телепортацией
    # Не активны, если кулдаун до телепортации < 0
    restrictions:
      # Запрет движения до рандомного телепорта
      move: true
      # Запрет получения урона до рандомного телепорта
      damage: true
    # Различные исключения телепортации
    avoid:
      # Блоки на которе игрока нельзя/можно будет телепортировать
      # Чтобы отключить проверку - поставьте list: []
      blocks:
        # Режим работы.
        # true - на эти блоки нельзя телепортировать false - можно телепортировать только на эти блоки
        blacklist: true
        list:
          - 'LAVA'
          - 'WATER'
      # Биомы в которых игрока нельзя/можно будет телепортировать
      # Чтобы отключить проверку - поставьте list: []
      biomes:
        # Режим работы.
        # true - в эти биомы нельзя телепортировать false - можно телепортировать только в эти биомы
        blacklist: true
        list:
          - 'OCEAN'
      # Блокировать ли телепортацию игрока в регионы WorldGuard
      regions: true
      # Блокировать ли телепортацию игрока в города Towny
      towns: false
    # Действия при телепортации
    # Доступные действия:
    # [MESSAGE] <сообщение> - отправить сообщение игроку
    # [SOUND] <id>;<громкость>;<тон> - отправить звук игроку
    # [TITLE] <тайтл>;<субтайтл>;<время_появления>;<время_показа>;<время_пропадания> - отправить тайтл игроку
    # [EFFECT] <эффект>;<уровень>;<время> - выдать эффект игроку
    # [CONSOLE] <команда> - выполнить команду от консоли
    actions:
      # Формат хекса - &#IIIDDD
      # Доступные плейсхолдеры 
      # %player% - ник игрока
      # %name% - имя канала телепортации
      # %time% - время до телепортации
      # %x% %y% %z% - координаты локации
      pre_teleport:
        - '[MESSAGE] &7&l(&5&lOvRandomTeleport&7) &6» &fВы будете телепортированы через %time% Не двигайтесь и не получайте урона.'
        - '[SOUND] BLOCK_NOTE_BLOCK_PLING;1;1'
      on_cooldown:
        3: 
          - '[TITLE] &aТелепорт через &63..'
        2:
          - '[TITLE] &aТелепорт через &62..'
        1: 
          - '[TITLE] &aТелепорт через &61..'
      after_teleport:
        - '[MESSAGE] &7&l(&5&lOvRandomTeleport&7) &6» &aУспешная телепортация! &fВы телепортировались на координаты: &2%x% %y% %z%.'
        - '[TITLE] &a&lУспех!;&fВы телепортировались на координаты: &2%x% %y% %z%.'
        - '[SOUND] ENTITY_PLAYER_LEVELUP;1;1'

  # Канал который будет телепортировать игрока рядом с другими игроками
  # Дистанция телепортации варьируется, от 30 до 60 блоков от игрока
  near:
    # Обязательный параметр
    name: 'Возле игроков'
    # Обязательный параметр
    type: NEAR_PLAYER
    # Обязательный параметр
    active_worlds:
      - 'world'
    # Необязательный параметр
    teleport_to_first_world: true
    # Необязательный параметр
    teleport_on_void: false
    # Необязательный параметр
    teleport_cost: 1000
    location_generation_options:
      shape: SQUARE
      min_x: -1000
      max_x: 1000
      min_z: -1000
      max_z: 1000
    # Необязательный параметр
    max_location_attemps: 50
    # Необязательный параметр
    invulnerable_after_teleport: 3
    # Необязательный параметр
    cooldown: 60
    # Необязательный параметр
    teleport_cooldown: 5
    # Необязательные параметры
    bossbar:
      enabled: true 
      title: '&fТелепортация через: &5%time%'
      color: WHITE
      style: SEGMENTED_12
    # Необязательные параметры
    restrictions:
      move: true
      damage: true
    # Необязательные параметры
    avoid:
      blocks:
        blacklist: true
        list:
          - 'LAVA'
          - 'WATER'
      biomes:
        blacklist: true
        list: []
      regions: true
      towns: false
    # Обязательный параметр
    actions:
      # Обязательный параметр. Укажите [] для отключения
      pre_teleport:
        - '[MESSAGE] &7&l(&5&lOvRandomTeleport&7) &6» &fВы будете телепортированы через %time% Не двигайтесь и не получайте урона.'
        - '[SOUND] BLOCK_NOTE_BLOCK_PLING;1;1'
      # Необязательный параметр
      on_cooldown:
        3: 
          - '[TITLE] &aТелепорт через &63..'
        2:
          - '[TITLE] &aТелепорт через &62..'
        1: 
          - '[TITLE] &aТелепорт через &61..'
      # Обязательный параметр. Укажите [] для отключения
      after_teleport:
        - '[MESSAGE] &7&l(&5&lOvRandomTeleport&7) &6» &aУспешная телепортация! &fВы телепортировались на координаты: &2%x% %y% %z%.'
        - '[TITLE] &a&lУспех!;&fВы телепортировались на координаты: &2%x% %y% %z%.'
        - '[SOUND] ENTITY_PLAYER_LEVELUP;1;1'
    # Необязательный параметр
    # Отдельные сообщения при использовании канала.
    # Если они не указаны - будут использованы дефолтные
    messages:
      prefix: '&7&l(&5&lOvRandomTeleport+&7&l) &6»&r'
      no_perms: '%prefix% &cУ вас не достаточно прав на использование канала телепортации к игрокам.'

  # Канал который будет телепортировать игрока рядом с регионами
  # Дистанция телепортации варьируется, от 30 до 60 блоков от игрока
  base:
    name: 'Возле баз'
    type: NEAR_REGION
    active_worlds:
      - 'world'
    location_generation_options:
      shape: SQUARE
      min_x: -1000
      max_x: 1000
      min_z: -1000
      max_z: 1000
    cooldown: 60
    restrictions:
      move: true
      damage: true
    actions:
      pre_teleport: []
      after_teleport:
        - '[MESSAGE] &7&l(&5&lOvRandomTeleport&7) &6» &aУспешная телепортация! &fВы телепортировались на координаты: &2%x% %y% %z%.'
        - '[TITLE] &a&lУспех!;&fВы телепортировались на координаты: &2%x% %y% %z%.'
        - '[SOUND] ENTITY_PLAYER_LEVELUP;1;1'
    messages:
      prefix: '&7&l(&5&lOvRandomTeleport+&7&l) &6»&r'
      no_perms: '%prefix% &cУ вас не достаточно прав на использование канала телепортации к базам.'

# Сообщения плагина
# Формат хекса - &#IIIDDD
messages:
  prefix: '&7&l(&5&lOvRandomTeleport&7&l) &6»&r'
  no_perms: '%prefix% &cУ вас не достаточно прав на использование данного канала.'
  invalid_world: '%prefix% &fВы не можете использовать данный канал рандомной телепортации в этом мире.'
  not_enough_money: '%prefix% &cУ вас не достаточно денег чтобы телепортироваться по данному каналу.'
  cooldown: '%prefix% &fВы еще не можете телепортироваться по данному каналу. Подождите еще %time%.'
  moved_on_teleport: '%prefix% &cВы двинулись! Телепортация отменена.'
  damaged_on_teleport: '%prefix% &cВы получили урон! Телепортация отменена.'
  fail_to_find_location: '%prefix% &6Не удалось подобрать необходимую локацию. Попробуйте снова позже!'
  already_teleporting: '%prefix% &cВы уже телепортируетесь!'
  incorrect_channel: '%prefix% &cУказанного канала рандомной телепортации не существует!'
  # Плейсхолдеры времени
  time:
    hours: ' ч. '
    minutes: ' мин. '
    seconds: ' сек. '
  # Раздел для админских команд
  admin:
    reload: '%prefix% &aПлагин успешно перезагружен!'
    unknown_argument: '%prefix% &cВы введи недопустимы(й/е) аргумент(ы) к команде!'
    player_not_found: '%prefix% &cУказанный игрок не найден!'
    admin_help: |-
      %prefix% Помощь по админ.командам.
      &a/rtp admin reload &f- перезагрузить плагин
      &a/rtp admin forceteleport <игрок> <канал> &f- телепортировать игрока по указанному каналу
  