name: OvRandomTeleport
version: '${project.version}'
author: OverwriteMC
main: ru.overwrite.rtp.Main
api-version: 1.16
softdepend: [Vault, WorldGuard, WorldEdit, Towny, PlayerPoints, PlaceholderAPI]
libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8
  - org.apache.commons:commons-math3:3.6.1
