name: OvRandomTeleport
version: '${project.version}'
author: OverwriteMC
main: ru.overwrite.rtp.Main
api-version: 1.13
softdepend: [Vault, WorldGuard, WorldEdit, Towny, PlayerPoints, PlaceholderAPI]
libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8
  - it.unimi.dsi:dsiutils:2.7.3
