name: OvRandomTeleport
version: '${project.version}'
author: OverwriteMC
main: ru.overwrite.rtp.Main
api-version: 1.13
softdepend: [Vault, WorldGuard, WorldEdit, Towny]
libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8
  - org.apache.commons:commons-lang3:3.14.0
