name: 'Возле баз'
type: NEAR_REGION
active_worlds:
  - 'world'
costs:
  # По умолчанию - VAULT
  money_type: PLAYERPOINTS
  money_cost: 100
location_generation_options:
  shape: SQUARE
  min_x: -1000
  max_x: 1000
  min_z: -1000
  max_z: 1000
cooldown:
  default_cooldown: 300
restrictions:
  move: true
  damage: true
actions:
  pre_teleport: []
  after_teleport:
    - '[MESSAGE] &7&l(&5&lOvRandomTeleport&7) &6» &aУспешная телепортация! &fВы телепортировались на координаты: &2%x% %y% %z%.'
    - '[TITLE] &a&lУспех!;&fВы телепортировались на координаты: &2%x% %y% %z%.'
    - '[SOUND] ENTITY_PLAYER_LEVELUP;1;1'
messages:
  prefix: '&7&l(&5&lOvRandomTeleport+&7&l) &6»&r'
  no_perms: '%prefix% &cУ вас не достаточно прав на использование канала телепортации к базам.'