name: OvRandomTeleport
version: '1.1.0'
author: OverwriteMC
main: ru.overwrite.rtp.Main
api-version: 1.13
softdepend: [Vault, WorldGuard, WorldEdit, Towny]
libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8
